index:
    path: /
    defaults: { _controller: SGSSiteBundle:Main:index }

sgs_books:
    path: /books
    defaults: { _controller: SGSSiteBundle:Main:books }

sgs_book_read:
    path: /book/{id}
    defaults: { _controller: SGSSiteBundle:Main:bookRead }